export default data;
const data = {
    products: [
        {
            _id:'1',
            name:'Modern Office set',
            category:'Clothes',
            image:'/images/p1.jpg',
            price: 120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Modern Office set',
            category:'Clothes',
            image:'/images/p2.jpg',
            price: 120,
            brand:'Nike',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Modern Office set',
            category:'Clothes',
            image:'/images/p3.jpg',
            price: 120,
            brand:'Nike',
            rating:3.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Modern Office set',
            category:'Clothes',
            image:'/images/p4.jpg',
            price: 120,
            brand:'Nike',
            rating:4.0,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Modern Office set',
            category:'Clothes',
            image:'/images/p5.jpg',
            price: 120,
            brand:'Nike',
            rating:5.0,
            numReviews:10,
            description: 'high quality product',
        },{
            _id:'6',
            name:'Modern Office set',
            category:'Clothes',
            image:'/images/p6.jpg',
            price: 120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
    ]
}